<!-- # [Link to video.]() -->

### Throwing Exceptions

An **exception** is an error that causes a program to end abruptly. We say that exceptions are **thrown** in C++, whereas in some other languages we say that exceptions are *raised*.

In C++, there is an `<exception>` file that defines all the types of exceptions. Here is [the documentation](https://legacy.cplusplus.com/reference/exception/exception/) for it. 

When we create our own functions, we can throw an exception using the keyword `throw`. When we throw an exception, we specify the exception message we want to display using `exception_name(message)`. When we catch an exception, we can get the error message using the `what()` method on the exception. Here is an example:

```cpp
/**
 * @author MissStrong
 */

#include <iostream>
#include <string>
#include <exception>
using namespace std;

/**
 * Takes a word (a string with only alphabet characters) and returns the number of capital letters in it.
 *
 * @param word
 */
int numberOfCapitalLetters(string word) {

    int count = 0; // keeps track of the number of capital letters seen so far
    
    // changes the string into an array of its individual characters and loops through them
    for (char c : word) {

      // checks whether the character is a letter
      if (isalpha(c)) {
        // checks whether the letter is capital
        if (isupper(c)) {
          count++;
        }
      } else {
        // the character is not a letter
        throw invalid_argument("Error: The word must contain only alphabet characters.");
      }
    }

    // the exception was not thrown so we're good to return the count
    return count;
  }
/**
 * Testing numberOfCapitalLetters().
 *
 * @return 0 if successful, 1 if unsuccessful
 */
int main() {
  try {
    cout << numberOfCapitalLetters("hello") << endl; // prints 0
    cout << numberOfCapitalLetters("Hello") << endl; // prints 1
    cout << numberOfCapitalLetters("HELLO") << endl; // prints 5
    cout << numberOfCapitalLetters("123") << endl; // throws an error
  } catch (invalid_argument exception) { // catches the error thrown from numberOfCapitalLetters("123")
    cerr << exception.what() << endl; // prints the error message to cerr
  }
}
```

In C++ we can also `throw` other things. For example, we could throw the error message as a string.

```cpp
throw "Error: The word must contain only alphabet characters.";
```

To catch a string we need to catch it as a constant character pointer `const char*`. We'll learn more about pointers later.

```cpp
catch (const char* errorMessage) {
  cerr << errorMessage << endl; // prints the error message to cerr
}
```   

Another option is to throw integers that represent categories of errors.

```cpp
throw 404;
```

```cpp
catch (int errorNumber) {
  if (errorNumber == 404) {
    cerr << "404 Error: Page not found." << endl;
  }
}
```

