### Exception Handling

Whenever we run a program that has errors, we may have noticed that Replit attempts to tells we what kind of error it is. 

For example, if we try to divide by zero, we get a message in the console saying that there was an **exception** called `java.lang.ArithmeticException`.

![](../../Images/Arithmetic_Exception.png)

An exception is a problem that occurs while a program is running. When an exception occurs, the Java runtime "throws" it. When an exception is thrown and our program doesn't "catch" it (i.e. it doesn't handle it), the program terminates abruptly. There are more than 450 kinds of exceptions built into Java; we can view these all on the [Java API documentation](https://docs.oracle.com/javase/7/docs/api/java/lang/Exception.html).

In order to avoid a program from terminating abruptly, we should consider possible exceptions that could occur in our methods.

Here is an example of a method that handles a division by zero error.

```java
public static int divideThreeInts(int a, int b, int c) {
    try {
        return a/b/c;
    } catch (ArithmeticException exception) {
        if (b == 0) System.out.println("Error. B cannot be zero.");
        if (c == 0) System.out.println("Error. C cannot be zero.");
        return 0;
    }
}
```

The content in the `try` block is run first. It tries to run the lines in the block; if an exception occurs, the exception is "thrown" and the rest of the block does not run. 

The content in the `catch` block runs only when the exception `ArithmeticException` has been thrown. It "catches" the exception.

If we want to catch any type of exception, we can do that with `Exception` although in general it's a better idea to specify the type of exception you want to catch.

```java
catch (Exception exception) { # catches any type of exception
```

If there are more lines of code us want to run regardless of whether the catch block is run, we can use a `finally` block. The `finally` block will run right after everything else even if another exception is thrown durin a catch.

```java
try {
    ...
} catch (ArithmeticException exception) {
    ...
} finally {
    ...
}
```

### NullPointerException

The null pointer exception is one of the most notorious exceptions in Java. The inventor of the null reference, Sir Charles Antony Richard Hoare, once said,

> *"I call it my billion-dollar mistake. It was the invention of the null reference in 1965â€¦ This has led to innumerable errors, vulnerabilities, and system crashes, which have probably caused a billion dollars of pain and damage in the last forty years".*

The null pointer exception occurs when a program tries to use an object reference that has a null value. We'll learn more about this in a later lesson.
